config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'lookup#search'

  post 'results' => 'lookup#results'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
        default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    belongs_to :user

	def full_name 
		"#{first_name} #{last_name}"
	end

	def full_address
		"#{address}, #{city}, #{state}, #{zip}"
	end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name) }

  devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :name) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :business_name, :address, :city, :state, :zip, :phone1, :phone2, :email, :avatar, :user_id)
    end
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  def search
  end

  def results
  	if params[:name] != nil
  		name_array = params[:name].split

  		@results = Contact.where(first_name: name_array[0], last_name: name_array[1], user_id: current_user.id)
  	elsif params[:city] != nil
  		@results = Contact.where(city: params[:city], user_id: current_user.id)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <strong>Upload Contact Image: </strong>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br>
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br>
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="well">

<p id="notice"><%= notice %></p>

<h1>All Contacts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Business</th>
      <th>Address</th>
      <th>Phone1</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.full_name %></td>
        <td><%= contact.business_name %></td>
        <td><%= contact.full_address %></td>
        <td><%= contact.phone1 %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-info" %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

</div>

app/views/contacts/new.html.erb
<div class="well">

<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @contact.avatar.url(:medium) %>
</p>

<p>
  <%= @contact.full_name %>
</p>

<p>
  <%= @contact.business_name %>
</p>

<p>
  <%= @contact.full_address %>
</p>

<p>
  <%= @contact.phone1 %>
</p>

<p>
  <%= @contact.phone2 %>
</p>

<p>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="background">

<% if user_signed_in? %>
<nav id="nav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">

      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to 'Search', root_path %></li>
      	<li><%= link_to 'New Contact', new_contact_path %></li>
      	<li><%= link_to 'All Contacts', contacts_path %></li>
      	<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li class="dropdown">
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/lookup/results.html.erb
<div class="well">

<h1>Contacts Found</h1>

<% if !@results.empty? %>
	<ul>
		<% @results.each do |contact| %>
		<li><%= contact.full_name %>, <%= contact.phone1 %></li>
		<% end %>
	</ul>
<% else %>
	<p>No contacts found by that name.</p>
	<p><%= link_to "Search for Another Name", root_path %></p>
<% end %>

</div>

app/views/lookup/search.html.erb
<div class="well">

<h1>Search for a Contact</h1>

<%= form_tag(results_path) do %>
	<div class="form-group">
 		<%= text_field_tag :name, nil, placeholder: "Search By Name (press enter to submit)", class: "form-control" %>
	</div>
<% end %>

<%= form_tag(results_path) do %>
	<div class="form-group">
 		<%= text_field_tag :city, nil, placeholder: "Search By City (press enter to submit)", class: "form-control" %>
	</div>
<% end %>


<p>
<%= link_to "Enter a New Contact", new_contact_path, class: "btn btn-info" %>
</p>

</div>